config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  resources :orders
  devise_for :users
  ActiveAdmin.routes(self)
  resource :users, only: [:show]
  resources :organizations
  resources :org_members
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# frozen_string_literal: true

require 'aasm'
class Order < ApplicationRecord
  include AASM
  extend Enumerize
  enumerize :aasm_state, in: %i[created working completed], default: :created

  aasm do
    state :created, initial: true
    state :working
    state :completed

    event :prepare do
      transitions from: :created, to: :working
    end

    event :work do
      transitions from: :working, to: :completed
    end

    event :rest do
      transitions from: :completed, to: :created
    end
  end

  paginates_per 5
  belongs_to :user
end

app/models/org_member.rb
# frozen_string_literal: true

class OrgMember < ApplicationRecord
  extend Enumerize
  enumerize :role, in: %i[operator org_admin]
  belongs_to :user
  belongs_to :organization
  paginates_per 5
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  belongs_to :user
  has_many :org_members, dependent: :destroy
  paginates_per 5
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  has_many :organizations, dependent: :destroy
  has_many :org_members, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
  end
  rescue_from Pundit::NotAuthorizedError, with: :org_member_not_admin

  private

  def org_member_not_admin
    flash[:success] = 'Operators can see only their own orders'
    redirect_to(orders_path)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!
  include DI[
    create_order: 'actions.orders.create'
  ]

  helper_method :sort_column, :sort_direction

  def index
    @orders = Order.order("#{sort_column} #{sort_direction}").page(params[:page]).where(user_id: current_user.id)
  end

  def new
    @order = Order.new
  end

  def create
    @order = create_order.(order_params.merge(user: current_user))
    flash[:success] = 'Order created successfully!'
    redirect_to order_path(@order)
  rescue ActiveRecord::NotNullViolation
    flash[:danger] = 'All rows must be filled!'
    redirect_back fallback_location: orders_path
  end

  def show
    @order = Order.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Order is missing!'
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name, :patronymic, :phone_number, :email, :weight, :length,
      :width, :height, :origin, :destination)
  end

  def sort_column
    Order.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/org_members_controller.rb
# frozen_string_literal: true

class OrgMembersController < ApplicationController
  before_action :authenticate_user!
  include DI[
    create_member: 'actions.org_members.create'
  ]

  def create
    @org_member = create_member.(org_member_params)
    flash[:success] = 'User invited!'
    redirect_back fallback_location: organizations_path
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'User not found!'
    redirect_back fallback_location: organizations_path
  end

  def show
    @org_members = OrgMember.all.page(params[:page])
    @organization = Organization.find(params[:id])
    @org_member = OrgMember.find_by!(user: current_user, organization: @organization)
    authorize @org_member, :show?
    @orders = Order.all
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'you are not member of this organization!'
    redirect_back fallback_location: organizations_path
  end

  private

  def permitted_params
    params.permit(:user_id, :organization_id, :role, :email)
  end

  def org_member_params
    {
      role: permitted_params[:role],
      user: User.find_by!(email: permitted_params[:email].strip),
      organization: Organization.find(permitted_params[:organization_id])
    }
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  include DI[
    create_organization: 'actions.organizations.create'
  ]

  def index
    @organizations = Organization.all.page(params[:page])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = create_organization.(organization_params.merge(user: current_user))
    @org_member = OrgMember.create(user: current_user, organization: @organization, role: 'org_admin')
    flash[:success] = 'Organization created successfully!'
    redirect_to organization_path(@organization)
  end

  def show
    @organization = Organization.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Organization is missing!'
    redirect_to organizations_path
  end

  private

  def organization_params
    params.require(:organization).permit(:title)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }, { class: css_class }
  end
end

app/views/layouts/_footer.html.haml
%footer.footer.mt-auto.py-3.bg-light
  .container
    %span.text-muted Alexey Leskov 2021

app/views/layouts/_header.html.haml
%body
  %header.p-3.bg-dark.text-white
    .container
      = link_to "Test App", root_path, id: "logo"
      .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{:href => "/"}
          %svg.bi.me-2{:height => "32", :width => "40"}
            %use{"xlink:href" => "#bootstrap"}
        %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        .text-end
          - if current_user
            = link_to "List of orders", orders_path, class: 'btn btn-warning'
            = link_to "New order", new_order_path, class: 'btn btn-warning'
            = link_to "Logout", destroy_user_session_path, :method => :delete, class: 'btn btn-warning'
            = link_to "#{current_user.email}", users_path, class: 'btn btn-warning'
          - else
            = link_to "Login", new_user_session_path, class: 'btn btn-warning'
            = link_to "Sign-up", new_user_registration_path, class: 'btn btn-warning'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Test application
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css", :integrity => "sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")

      = yield
      = render 'layouts/footer'

app/views/orders/index.html.haml
%h1 List of Orders

%table{:width=> "100%", :border => 1}
  %body
    %tr
      %td Order number
      %td First name:
      %td Patronymic:
      %td Last name:
      %td Phone number:
      %td Email:
      %td Origin
      %td Destination
      %td Distance
      %td Price
    - @orders.each do |object|
      %tr
        %td= link_to object.order_number, object
        %td= object.first_name
        %td= object.patronymic
        %td= object.last_name
        %td= object.phone_number
        %td= object.email
        %td= object.origin
        %td= object.destination
        %td= object.distance
        %td= object.price
%tr
  Sorting by:
  %th= sortable "created_at"
  %th= sortable "price"
  %th= sortable "distance"

= paginate @orders

app/views/orders/new.html.haml
%h1 Greetings! How about create a new order?
.row
  .col-md-6.col-md-offset-3
    = form_with model: @order, local: true do |f|

      = f.hidden_field :user_id
      = f.label :first_name
      = f.text_field :first_name
      - @order.errors.full_messages_for(:first_name).each do |message|
        %div= message

      = f.label :patronymic
      = f.text_field :patronymic
      - @order.errors.full_messages_for(:patronymic).each do |message|
        %div= message

      = f.label :last_name
      = f.text_field :last_name
      - @order.errors.full_messages_for(:last_name).each do |message|
        %div= message

      = f.label :phone_number
      = f.text_field :phone_number
      - @order.errors.full_messages_for(:phone_number).each do |message|
        %div= message

      = f.label :email
      = f.email_field :email
      - @order.errors.full_messages_for(:email).each do |message|
        %div= message

      = f.label :weight
      = f.number_field :weight
      - @order.errors.full_messages_for(:weight).each do |message|
        %div= message

      = f.label :length
      = f.number_field :length
      - @order.errors.full_messages_for(:length).each do |message|
        %div= message

      = f.label :width
      = f.number_field :width
      - @order.errors.full_messages_for(:width).each do |message|
        %div= message

      = f.label :height
      = f.number_field :height
      - @order.errors.full_messages_for(:height).each do |message|
        %div= message

      = f.label :origin
      = f.text_field :origin
      - @order.errors.full_messages_for(:origin).each do |message|
        %div= message

      = f.label :destination
      = f.text_field :destination
      - @order.errors.full_messages_for(:destination).each do |message|
        %div= message

      = f.submit "Create new order", class: "btn btn-primary"

app/views/orders/show.html.haml
.row
  %aside.col-md-4
    %section.poll_info

      %h1
        = 'Order №' + @order.order_number.to_s

      %h2
        %u Orderer:
        %h3
          = @order.first_name
          = @order.patronymic
          = @order.last_name
      %h3
        %u Phone number:
        = @order.phone_number

      %h3
        %u Email:
        = @order.email
      %h3
        %u Cargo parameters:
        %h4
          Weight:
          = @order.weight
        %h4
          Length:
          = @order.length
        %h4
          Width:
          = @order.width
        %h4
          Height:
          = @order.height
      %h3
        %u Origin:
        = @order.origin
      %h3
        %u Destination:
        = @order.destination

      %h3
        %u Distance:
        = @order.distance.to_s + ' km'
      %h3
        %u Price:
        = @order.price.to_s + ' roubles'

app/views/org_members/show.html.haml
%h1 It's your profile #{@org_member.user.email}
%h3 You are admin.
= paginate @org_members.where(role: 'operator')
%h3 Operators:
%table{:width=> "100%", :border => 2}
  %body
    %tr
      %td User
      %td List of orders
    - @org_members.where(organization_id: @organization.id, role: 'operator').each do |object|
      %tr
        %td= object.user.email
        - @orders.where(user: object).each do |object|
          %td= link_to object.order_number, object
= link_to "your personal orders", orders_path, class: 'btn btn-warning'

app/views/organizations/_org_members.html.haml
%h2 List of members:

- if @admin
  %h3 You are admin.
  %h3 Operators:
  = paginate @org_members.where(role: 'operator')
  %table{:width=> "100%", :border => 2}
    %body
      %tr
        %td Role
        %td User
        %td List of orders
      - @org_members.where(organization_id: @organization.id, role: 'operator').each do |object|
        %tr
          %td= object.role
          %td= object.user.email
          - @orders.where(user: object).each do |object|
            %td= link_to object.order_number, object
- else
  %h3 You are operator
  %h3 Your orders:
  = paginate @orders.where(id: current_user)
  %table{:width=> "75%", :border => 2}
    %body
      %tr
        %td Order number
        %td Origin
        %td Destination
        %td Distance
        %td Price
      - @orders.where(user: current_user).each do |object|
        %tr
          %td= link_to object.order_number, object
          %td= object.origin
          %td= object.destination
          %td= object.distance
          %td= object.price

app/views/organizations/index.html.haml
%h1 List of Organizations
= render  @organizations

%table{:width=> "100%", :border => 1}
  %body
    %tr
      %td Title
    - @organizations.each do |object|
      %tr
        %td= link_to object.title, object
= paginate @organizations

app/views/organizations/new.html.haml
%h1 Greetings! #{current_user.email} Let's create a new organization!
.row
  .col-md-6.col-md-offset-3
    = form_with model: @organization, local: true do |f|

      = f.hidden_field :user_id
      = f.label :title
      = f.text_field :title
      - @organization.errors.full_messages_for(:title).each do |message|
        %div= message
      = f.submit "Create new organization", class: "btn btn-primary"

app/views/organizations/show.html.haml
%p
Hello there!
%p
its #{@organization.title} organization
%p
You can invite other users to your organization

.row
  .col-md-6.col-md-offset-3
    = form_tag('/org_members', :method => "post") do

      = hidden_field_tag :organization_id, @organization.id
      = label_tag :email, "Email of user"
      = email_field_tag :email, '', placeholder: User.human_attribute_name(:email)
      = label :role, "role"
      = select_tag :role, options_for_select(OrgMember.role.options)
      = submit_tag "invite user", class: "btn btn-primary"


= link_to "Your Profile", org_member_path, class: 'btn btn-warning'

app/views/pages/index.html.haml
%html
%head
%title TestPoll
%body
%h1 Welcome to Test Application!
%p
  - if current_user
    = link_to "List of organizations", organizations_path, class: 'btn btn-warning'
  - else
    %h2 Please  sign up or log in to continue!

app/views/users/show.html.haml
%h1
  = current_user.email

%p
  = image_tag current_user.avatar.url(:thumb) if current_user.avatar?
  Its a great avatar, isnt it?

%p
  = link_to "Create Organization", new_organization_path, class: 'btn btn-warning'
  Wanna create a new organization?